apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sentic-signal-chart.fullname" . }}-config
data:
  PROVIDER: {{ .Values.config.provider | quote }}
  TICKER: {{ .Values.config.ticker | quote }}
  NEWS_LOOKBACK_MINUTES: {{ .Values.config.newsLookbackMinutes | quote }}
  NEWS_RELEVANCE_THRESHOLD: {{ .Values.config.newsRelevanceThreshold | quote }}
  RABBITMQ_HOST: {{ .Values.rabbitmq.host | quote }}
  RABBITMQ_PORT: {{ .Values.rabbitmq.port | quote }}
  RABBITMQ_QUEUE: {{ .Values.rabbitmq.queue | quote }}
  RABBITMQ_USERNAME: {{ .Values.rabbitmq.username | quote }}
