#!/usr/bin/env bash
# =============================================================================
# scripts/gen-env.sh
#
# Generates a local .env file from deploy/sentic-signal-chart/values.yaml.
# Use this when developing directly in VS Code instead of running in k8s.
#
# Requires: yq (https://github.com/mikefarah/yq)
#   brew install yq
#
# Usage:
#   ./scripts/gen-env.sh                  # writes to .env
#   ./scripts/gen-env.sh --dry-run        # prints to stdout, no write
#
# Secrets (API keys) are NOT stored in values.yaml. Add them to a local
# .env.secrets file and they will be appended automatically if it exists.
# Never commit .env or .env.secrets to git.
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
VALUES="${REPO_ROOT}/deploy/sentic-signal-chart/values.yaml"
ENV_OUT="${REPO_ROOT}/.env"
ENV_SECRETS="${REPO_ROOT}/.env.secrets"
DRY_RUN=false

for arg in "$@"; do
  case $arg in
    --dry-run) DRY_RUN=true ;;
    *) echo "Unknown argument: $arg" >&2; exit 1 ;;
  esac
done

if ! command -v yq &>/dev/null; then
  echo "Error: 'yq' is required but not found. Install with: brew install yq" >&2
  exit 1
fi

generate() {
  cat <<EOF
# Auto-generated by scripts/gen-env.sh from values.yaml.
# Do not edit by hand — re-run the script to regenerate.
# Secrets (API keys) come from .env.secrets, not here.

PROVIDER=$(yq '.config.provider' "${VALUES}")
TICKER=$(yq '.config.ticker' "${VALUES}")
NEWS_LOOKBACK_MINUTES=$(yq '.config.newsLookbackMinutes' "${VALUES}")
NEWS_RELEVANCE_THRESHOLD=$(yq '.config.newsRelevanceThreshold' "${VALUES}")

# RabbitMQ — override host to localhost for local development.
RABBITMQ_HOST=localhost
RABBITMQ_PORT=$(yq '.rabbitmq.port' "${VALUES}")
RABBITMQ_QUEUE=$(yq '.rabbitmq.queue' "${VALUES}")
# RabbitMQ credentials — defaults match local Docker Compose (guest/guest).
# In k8s these are injected from the operator-generated Secret.
RABBITMQ_USERNAME=guest
RABBITMQ_PASSWORD=guest
EOF
}

if $DRY_RUN; then
  generate
  echo ""
  echo "# (dry-run: not written to disk)"
  exit 0
fi

generate > "${ENV_OUT}"

# Append secrets if .env.secrets exists.
if [[ -f "${ENV_SECRETS}" ]]; then
  echo "" >> "${ENV_OUT}"
  echo "# --- Secrets from .env.secrets ---" >> "${ENV_OUT}"
  cat "${ENV_SECRETS}" >> "${ENV_OUT}"
  echo "Appended secrets from .env.secrets"
else
  echo ""
  echo "Note: No .env.secrets found. API keys are not set."
  echo "Create .env.secrets with your ALPHA_VANTAGE_KEY, FINNHUB_API_KEY, etc."
fi

echo "Written to ${ENV_OUT}"
